package com.ferdousmunny.cgpacalculator.util

import androidx.compose.runtime.compositionLocalOf

enum class AppLanguage { ENGLISH, BANGLA }

/**
 * All user-facing text in the app, in one place, in both supported languages.
 * This avoids Android's XML string-resource + Activity-recreate approach so
 * the language can switch instantly while the app is running.
 */
data class AppStrings(
    val appName: String,
    val welcomeTagline: String,

    val loginTitle: String,
    val registerTitle: String,
    val fullNameHint: String,
    val emailHint: String,
    val passwordHint: String,
    val confirmPasswordHint: String,
    val departmentLabel: String,
    val loginButton: String,
    val registerButton: String,
    val noAccountText: String,
    val haveAccountText: String,
    val forgotPassword: String,

    val tabMyCourses: String,
    val tabRetake: String,
    val tabAddCourses: String,

    val currentCgpa: String,
    val totalCredit: String,
    val noCoursesMessage: String,
    val searchHint: String,
    val noSearchResults: String,
    val sortLabel: String,
    val sortDefault: String,
    val sortByName: String,
    val sortByGrade: String,
    val sortByCredit: String,
    val addCourse: String,
    val courseNameHint: String,
    val creditHint: String,
    val gradeLabel: String,
    val cancel: String,
    val save: String,
    val ok: String,
    val delete: String,
    val fixErrors: String,
    val deleteConfirmTitle: String,
    val deleteConfirmMessage: String,
    val courseDeletedMessage: String,
    val editCourseTitle: String,
    val courseUpdatedMessage: String,
    val removedFromListMessage: String,
    val addToListConfirmTitle: String,
    val addToListConfirmMessage: String,
    val courseAddedToListMessage: String,
    val saveCompletedConfirmTitle: String,
    val saveCompletedConfirmMessage: String,
    val coursesSavedMessage: String,
    val applyRetakeConfirmTitle: String,
    val applyRetakeConfirmMessage: String,
    val retakesAppliedMessage: String,

    val retakeSelectCourse: String,
    val retakeNewGrade: String,
    val cgpaAfterRetake: String,
    val cgpaWillIncrease: String,
    val cgpaWillDecrease: String,
    val cgpaNoChange: String,
    val applyRetake: String,
    val retakeNote: String,
    val retakeInstruction: String,
    val retakeApplySelected: String,
    val retakeNoneSelected: String,

    val tabTargetCgpa: String,
    val targetCgpaInstruction: String,
    val targetCgpaLabel: String,
    val remainingCreditsLabel: String,
    val calculateButton: String,
    val requiredGpaLabel: String,
    val targetAchievableMessage: String,
    val targetNotAchievableMessage: String,
    val targetAlreadyMetMessage: String,

    val tabTrend: String,
    val trendInstruction: String,
    val trendNotEnoughData: String,
    val trendChartTitle: String,

    val tabInsights: String,
    val insightsNoData: String,
    val creditProgressTitle: String,
    val creditsCompletedLabel: String,
    val creditsRequiredLabel: String,
    val creditsRemainingLabel: String,
    val creditsGoalReachedMessage: String,
    val bestSemesterLabel: String,
    val worstSemesterLabel: String,
    val gradeDistributionTitle: String,
    val totalCreditsRequiredSetting: String,
    val totalCreditsRequiredHint: String,
    val remindersSetting: String,
    val semesterReminderLabel: String,
    val customRemindersLabel: String,
    val addReminderButton: String,
    val reminderTitleHint: String,
    val reminderDefaultMessage: String,

    val addCoursesInstruction: String,
    val addToList: String,
    val possibleCourses: String,
    val projectedCgpa: String,
    val saveAllAsCompleted: String,

    val importCourses: String,
    val importFromFile: String,
    val exportPdf: String,
    val backupExport: String,
    val backupImport: String,
    val backupExportSuccess: String,
    val backupImportNothingFound: String,
    val importFormatHint: String,
    val importSuccess: String,
    val importNothingFound: String,
    val importReviewTitle: String,
    val importAddAll: String,
    val importProcessing: String,

    val menuHome: String,
    val menuSettings: String,
    val menuAbout: String,
    val logout: String,
    val logoutConfirmTitle: String,
    val logoutConfirmMessage: String,
    val yes: String,
    val no: String,

    val settingsTitle: String,
    val departmentSetting: String,
    val universitySetting: String,
    val universityHint: String,
    val semestersSetting: String,
    val addSemesterHint: String,
    val add: String,
    val noSemesterGroup: String,
    val semesterLabel: String,
    val languageSetting: String,
    val darkModeSetting: String,
    val themeModeSetting: String,
    val themeModeSystem: String,
    val themeModeLight: String,
    val themeModeDark: String,
    val rateUsTitle: String,
    val rateUsMessage: String,
    val rateUsNow: String,
    val rateUsLater: String,
    val rateUsNever: String,
    val biometricLockSetting: String,
    val biometricLockLabel: String,
    val lockScreenTitle: String,
    val lockScreenSubtitle: String,
    val lockScreenRetryButton: String,
    val emailVerificationSetting: String,
    val emailNotVerifiedMessage: String,
    val resendVerificationButton: String,
    val verificationEmailSentMessage: String,
    val deleteAccountSetting: String,
    val deleteAccountButton: String,
    val deleteAccountConfirmMessage: String,
    val deleteAccountFailedMessage: String,
    val courseNotesHint: String,
    val courseNotesLabel: String,
    val viewNotesTitle: String,
    val gradingScaleSetting: String,
    val gradingScale4: String,
    val gradingScale5: String,
    val gradingScaleNote: String,
    val saveScenarioButton: String,
    val scenarioNameHint: String,
    val savedScenariosLabel: String,
    val loadScenarioButton: String,
    val scenarioSavedMessage: String,
    val scenarioDeletedMessage: String,
    val scenarioLoadedMessage: String,
    val changePassword: String,
    val changePasswordSent: String,
    val clearData: String,
    val clearDataConfirm: String,
    val dataClearedMessage: String,
    val appVersion: String,

    val aboutTitle: String,
    val aboutDescription: String,
    val featuresTitle: String,
    val feature1: String,
    val feature2: String,
    val feature3: String,
    val feature4: String,
    val developedBy: String,
    val university: String,
    val contact: String
)

val EnglishStrings = AppStrings(
    appName = "CGPA Calculator",
    welcomeTagline = "Track your academic journey with confidence",

    loginTitle = "Welcome Back",
    registerTitle = "Create Account",
    fullNameHint = "Full Name",
    emailHint = "Email",
    passwordHint = "Password",
    confirmPasswordHint = "Confirm Password",
    departmentLabel = "Department",
    loginButton = "Log In",
    registerButton = "Create Account",
    noAccountText = "Don't have an account? Sign up",
    haveAccountText = "Already have an account? Log in",
    forgotPassword = "Forgot Password?",

    tabMyCourses = "My Courses",
    tabRetake = "Retake Calculator",
    tabAddCourses = "Future Courses",

    currentCgpa = "Current CGPA",
    totalCredit = "Total Credits",
    noCoursesMessage = "No courses added yet.\nTap + to add one, or import from a file.",
    searchHint = "Search courses...",
    noSearchResults = "No courses match your search",
    sortLabel = "Sort",
    sortDefault = "Default Order",
    sortByName = "Name (A-Z)",
    sortByGrade = "Grade (High-Low)",
    sortByCredit = "Credit (High-Low)",
    addCourse = "Add Course",
    courseNameHint = "Course Name / Code",
    creditHint = "Credit Hours (e.g. 3)",
    gradeLabel = "Grade",
    cancel = "Cancel",
    save = "Save",
    ok = "OK",
    delete = "Delete",
    fixErrors = "Please enter a valid name and credit",
    deleteConfirmTitle = "Delete Course",
    deleteConfirmMessage = "Are you sure you want to delete this course? This can't be undone.",
    courseDeletedMessage = "Course deleted",
    editCourseTitle = "Edit Course",
    courseUpdatedMessage = "Course updated",
    removedFromListMessage = "Removed from list",
    addToListConfirmTitle = "Add Course",
    addToListConfirmMessage = "Add this course to your planned list?",
    courseAddedToListMessage = "Added to planned list",
    saveCompletedConfirmTitle = "Save as Completed",
    saveCompletedConfirmMessage = "Save these planned courses as completed courses? This will add them to My Courses.",
    coursesSavedMessage = "Courses saved to My Courses",
    applyRetakeConfirmTitle = "Apply Retakes",
    applyRetakeConfirmMessage = "Apply the new grades to the selected courses? Your saved CGPA will update.",
    retakesAppliedMessage = "Retake(s) applied",

    retakeSelectCourse = "Select course to retake",
    retakeNewGrade = "New expected grade",
    cgpaAfterRetake = "CGPA After Retake",
    cgpaWillIncrease = "CGPA will increase by",
    cgpaWillDecrease = "CGPA will decrease by",
    cgpaNoChange = "CGPA will remain unchanged",
    applyRetake = "Save This Retake Result",
    retakeNote = "* Your actual result only changes when you tap Apply. Until then this is just a preview.",
    retakeInstruction = "Check the courses you're retaking and pick a new grade for each. The preview below updates live.",
    retakeApplySelected = "Apply Selected Retakes",
    retakeNoneSelected = "Select at least one course to retake",

    tabTargetCgpa = "Target CGPA",
    targetCgpaInstruction = "Enter the CGPA you want to reach, and how many credits you have left, to see what average grade you need in those remaining credits.",
    targetCgpaLabel = "Target CGPA (e.g. 3.75)",
    remainingCreditsLabel = "Remaining Credits",
    calculateButton = "Calculate",
    requiredGpaLabel = "Required Average GPA",
    targetAchievableMessage = "You can reach this if you average this grade point in your remaining courses.",
    targetNotAchievableMessage = "Not possible -- even straight A+ in every remaining course won't reach this target.",
    targetAlreadyMetMessage = "You've already reached this CGPA!",

    tabTrend = "CGPA Trend",
    trendInstruction = "See how your cumulative CGPA has changed over each semester.",
    trendNotEnoughData = "Add courses with a semester assigned to at least 2 different semesters to see your trend.",
    trendChartTitle = "Cumulative CGPA by Semester",

    tabInsights = "Insights",
    insightsNoData = "Add some courses to see your insights here.",
    creditProgressTitle = "Credit Progress",
    creditsCompletedLabel = "Completed",
    creditsRequiredLabel = "Required",
    creditsRemainingLabel = "Remaining",
    creditsGoalReachedMessage = "You've completed all required credits!",
    bestSemesterLabel = "Best Semester",
    worstSemesterLabel = "Toughest Semester",
    gradeDistributionTitle = "Grade Distribution",
    totalCreditsRequiredSetting = "Total Credits Required to Graduate",
    totalCreditsRequiredHint = "e.g. 130",
    remindersSetting = "Reminders",
    semesterReminderLabel = "Remind me every ~3 months to update my CGPA",
    customRemindersLabel = "Custom Reminders",
    addReminderButton = "Add Reminder",
    reminderTitleHint = "e.g. Result Day, Exam Date",
    reminderDefaultMessage = "Don't forget to check this!",

    addCoursesInstruction = "Add courses you plan to take next, with your expected grade:",
    addToList = "Add to List",
    possibleCourses = "Planned Courses",
    projectedCgpa = "Projected CGPA",
    saveAllAsCompleted = "Save These as Completed Courses",

    importCourses = "Import Courses",
    importFromFile = "Import",
    exportPdf = "Export as PDF",
    backupExport = "Export Backup (JSON)",
    backupImport = "Import Backup (JSON)",
    backupExportSuccess = "Backup file saved",
    backupImportNothingFound = "No valid courses found in this backup file",
    importFormatHint = "Supported: .csv, .txt, .pdf, or a photo of your mark-sheet/transcript.\n\nSimple format: Course Name, Credit, Grade\nExample: Data Structures, 3, A\n\nOfficial transcripts (with Course Code, Description, Credit, Grade columns) are also supported directly -- no need to reformat them. OCR reading isn't always perfect, so always check the preview list before adding, and use a clear, well-lit, non-blurry photo for best results.",
    importSuccess = "course(s) imported",
    importNothingFound = "No valid courses found in this file",
    importReviewTitle = "Courses Found",
    importAddAll = "Add All",
    importProcessing = "Reading file...",

    menuHome = "Home",
    menuSettings = "Settings",
    menuAbout = "About",
    logout = "Log Out",
    logoutConfirmTitle = "Log Out",
    logoutConfirmMessage = "Are you sure you want to log out?",
    yes = "Yes",
    no = "No",

    settingsTitle = "Settings",
    departmentSetting = "Department",
    universitySetting = "University",
    universityHint = "e.g. ADUST",
    semestersSetting = "Semesters",
    addSemesterHint = "e.g. Spring 2026",
    add = "Add",
    noSemesterGroup = "Unassigned",
    semesterLabel = "Semester",
    languageSetting = "App Language",
    darkModeSetting = "Dark Mode",
    themeModeSetting = "Appearance",
    themeModeSystem = "System Default",
    themeModeLight = "Light",
    themeModeDark = "Dark",
    rateUsTitle = "Enjoying CGPA Calculator?",
    rateUsMessage = "A quick rating on the Play Store helps a lot and takes just a few seconds.",
    rateUsNow = "Rate Now",
    rateUsLater = "Later",
    rateUsNever = "No Thanks",
    biometricLockSetting = "Biometric Lock",
    biometricLockLabel = "Require fingerprint/face to open the app",
    lockScreenTitle = "App Locked",
    lockScreenSubtitle = "Unlock with your fingerprint, face, or device PIN to continue",
    lockScreenRetryButton = "Try Again",
    emailVerificationSetting = "Email Verification",
    emailNotVerifiedMessage = "Your email address hasn't been verified yet.",
    resendVerificationButton = "Resend Verification Email",
    verificationEmailSentMessage = "Verification email sent -- check your inbox",
    deleteAccountSetting = "Delete Account",
    deleteAccountButton = "Delete My Account",
    deleteAccountConfirmMessage = "This permanently deletes your account and all saved courses. This can't be undone. If this fails, log out and log back in, then try again.",
    deleteAccountFailedMessage = "Couldn't delete account. Please log out, log back in, and try again.",
    courseNotesHint = "Notes (optional) -- syllabus reminders, chapter list, etc.",
    courseNotesLabel = "Notes",
    viewNotesTitle = "Course Notes",
    gradingScaleSetting = "Grading Scale",
    gradingScale4 = "4.00 Scale",
    gradingScale5 = "5.00 Scale",
    gradingScaleNote = "Changes the grade options shown when adding new courses. Courses you've already added keep their original grade points.",
    saveScenarioButton = "Save as Scenario",
    scenarioNameHint = "Scenario name, e.g. Best Case",
    savedScenariosLabel = "Saved Scenarios",
    loadScenarioButton = "Load",
    scenarioSavedMessage = "Scenario saved",
    scenarioDeletedMessage = "Scenario deleted",
    scenarioLoadedMessage = "Scenario loaded",
    changePassword = "Change Password",
    changePasswordSent = "Password reset link sent to your email",
    clearData = "Clear All Course Data",
    clearDataConfirm = "This will permanently delete all your saved courses. Continue?",
    dataClearedMessage = "All course data has been cleared",
    appVersion = "App Version",

    aboutTitle = "About This App",
    aboutDescription = "CGPA Calculator helps university students track their CGPA, plan retakes, and project future results -- all in one simple, easy to use app.",
    featuresTitle = "Features",
    feature1 = "Track completed courses and current CGPA",
    feature2 = "Simulate retake results before committing",
    feature3 = "Plan future semesters with projected CGPA",
    feature4 = "Bulk import courses from CSV or TXT files",
    developedBy = "Developed by",
    university = "University",
    contact = "Contact"
)

val BanglaStrings = AppStrings(
    appName = "CGPA ক্যালকুলেটর",
    welcomeTagline = "আপনার একাডেমিক যাত্রা সহজে ট্র্যাক করুন",

    loginTitle = "স্বাগতম",
    registerTitle = "অ্যাকাউন্ট তৈরি করুন",
    fullNameHint = "পুরো নাম",
    emailHint = "ইমেইল",
    passwordHint = "পাসওয়ার্ড",
    confirmPasswordHint = "পাসওয়ার্ড নিশ্চিত করুন",
    departmentLabel = "ডিপার্টমেন্ট",
    loginButton = "লগইন",
    registerButton = "অ্যাকাউন্ট তৈরি করুন",
    noAccountText = "অ্যাকাউন্ট নেই? সাইন আপ করুন",
    haveAccountText = "অ্যাকাউন্ট আছে? লগইন করুন",
    forgotPassword = "পাসওয়ার্ড ভুলে গেছেন?",

    tabMyCourses = "আমার কোর্স",
    tabRetake = "রিটেক ক্যালকুলেটর",
    tabAddCourses = "ভবিষ্যৎ কোর্স",

    currentCgpa = "বর্তমান CGPA",
    totalCredit = "মোট ক্রেডিট",
    noCoursesMessage = "এখনো কোনো কোর্স যোগ করা হয়নি।\n+ চাপুন অথবা ফাইল থেকে ইমপোর্ট করুন।",
    searchHint = "কোর্স খুঁজুন...",
    noSearchResults = "আপনার সার্চের সাথে মিলে এমন কোনো কোর্স নেই",
    sortLabel = "সাজান",
    sortDefault = "ডিফল্ট অর্ডার",
    sortByName = "নাম (A-Z)",
    sortByGrade = "গ্রেড (বেশি-কম)",
    sortByCredit = "ক্রেডিট (বেশি-কম)",
    addCourse = "কোর্স যোগ করুন",
    courseNameHint = "কোর্সের নাম / কোড",
    creditHint = "ক্রেডিট আওয়ার (যেমন 3)",
    gradeLabel = "গ্রেড",
    cancel = "বাতিল",
    save = "সংরক্ষণ",
    ok = "ঠিক আছে",
    delete = "মুছুন",
    fixErrors = "সঠিক নাম এবং ক্রেডিট দিন",
    deleteConfirmTitle = "কোর্স মুছুন",
    deleteConfirmMessage = "আপনি কি নিশ্চিত এই কোর্সটি মুছতে চান? এটা আর ফিরিয়ে আনা যাবে না।",
    courseDeletedMessage = "কোর্স মুছে ফেলা হয়েছে",
    editCourseTitle = "কোর্স এডিট করুন",
    courseUpdatedMessage = "কোর্স আপডেট করা হয়েছে",
    removedFromListMessage = "তালিকা থেকে সরানো হয়েছে",
    addToListConfirmTitle = "কোর্স যোগ করুন",
    addToListConfirmMessage = "এই কোর্সটি আপনার পরিকল্পিত তালিকায় যোগ করবেন?",
    courseAddedToListMessage = "পরিকল্পিত তালিকায় যোগ করা হয়েছে",
    saveCompletedConfirmTitle = "সম্পন্ন হিসেবে সংরক্ষণ করুন",
    saveCompletedConfirmMessage = "এই পরিকল্পিত কোর্সগুলো সম্পন্ন কোর্স হিসেবে সংরক্ষণ করবেন? এটা My Courses-এ যোগ হয়ে যাবে।",
    coursesSavedMessage = "কোর্সগুলো My Courses-এ সংরক্ষণ করা হয়েছে",
    applyRetakeConfirmTitle = "রিটেক প্রয়োগ করুন",
    applyRetakeConfirmMessage = "নির্বাচিত কোর্সগুলোতে নতুন গ্রেড প্রয়োগ করবেন? আপনার সংরক্ষিত CGPA আপডেট হয়ে যাবে।",
    retakesAppliedMessage = "রিটেক প্রয়োগ করা হয়েছে",

    retakeSelectCourse = "রিটেক করার কোর্স বেছে নিন",
    retakeNewGrade = "নতুন সম্ভাব্য গ্রেড",
    cgpaAfterRetake = "রিটেকের পর CGPA",
    cgpaWillIncrease = "CGPA বাড়বে",
    cgpaWillDecrease = "CGPA কমবে",
    cgpaNoChange = "CGPA অপরিবর্তিত থাকবে",
    applyRetake = "এই রিটেক ফলাফল সংরক্ষণ করুন",
    retakeNote = "* Apply চাপলেই শুধু আসল রেজাল্টে পরিবর্তন হবে। তার আগে এটা শুধু প্রিভিউ।",
    retakeInstruction = "যেসব কোর্স রিটেক দিচ্ছেন সেগুলোতে টিক দিন আর নতুন গ্রেড বেছে নিন। নিচের প্রিভিউ সাথে সাথে আপডেট হবে।",
    retakeApplySelected = "নির্বাচিত রিটেকগুলো Apply করুন",
    retakeNoneSelected = "কমপক্ষে একটা কোর্স নির্বাচন করুন",

    tabTargetCgpa = "টার্গেট CGPA",
    targetCgpaInstruction = "তুমি কত CGPA পেতে চাও আর কত ক্রেডিট বাকি আছে দাও, দেখবে বাকি ক্রেডিটে গড়ে কত গ্রেড পয়েন্ট লাগবে।",
    targetCgpaLabel = "টার্গেট CGPA (যেমন 3.75)",
    remainingCreditsLabel = "বাকি ক্রেডিট",
    calculateButton = "হিসাব করুন",
    requiredGpaLabel = "প্রয়োজনীয় গড় GPA",
    targetAchievableMessage = "বাকি কোর্সগুলোতে এই গ্রেড পয়েন্ট গড়ে রাখতে পারলে এটা সম্ভব।",
    targetNotAchievableMessage = "সম্ভব না -- বাকি সব কোর্সে A+ পেলেও এই টার্গেটে পৌঁছানো যাবে না।",
    targetAlreadyMetMessage = "তুমি ইতিমধ্যে এই CGPA পেয়ে গেছ!",

    tabTrend = "CGPA ট্রেন্ড",
    trendInstruction = "প্রতি সেমিস্টারে তোমার সামগ্রিক CGPA কীভাবে বদলেছে তা দেখো।",
    trendNotEnoughData = "অন্তত ২টা ভিন্ন সেমিস্টারে কোর্স যোগ করলে ট্রেন্ড দেখতে পাবে।",
    trendChartTitle = "সেমিস্টার অনুযায়ী সামগ্রিক CGPA",

    tabInsights = "ইনসাইটস",
    insightsNoData = "ইনসাইটস দেখতে কিছু কোর্স যোগ করো।",
    creditProgressTitle = "ক্রেডিট অগ্রগতি",
    creditsCompletedLabel = "সম্পন্ন",
    creditsRequiredLabel = "প্রয়োজনীয়",
    creditsRemainingLabel = "বাকি",
    creditsGoalReachedMessage = "তুমি সব প্রয়োজনীয় ক্রেডিট সম্পন্ন করেছ!",
    bestSemesterLabel = "সেরা সেমিস্টার",
    worstSemesterLabel = "সবচেয়ে কঠিন সেমিস্টার",
    gradeDistributionTitle = "গ্রেড বিতরণ",
    totalCreditsRequiredSetting = "গ্র্যাজুয়েশনের জন্য মোট প্রয়োজনীয় ক্রেডিট",
    totalCreditsRequiredHint = "যেমন 130",
    remindersSetting = "রিমাইন্ডার",
    semesterReminderLabel = "প্রতি ৩ মাস পর পর CGPA আপডেট করার রিমাইন্ডার দাও",
    customRemindersLabel = "কাস্টম রিমাইন্ডার",
    addReminderButton = "রিমাইন্ডার যোগ করুন",
    reminderTitleHint = "যেমন Result Day, Exam Date",
    reminderDefaultMessage = "এটা চেক করতে ভুলো না!",

    addCoursesInstruction = "সামনে যেসব কোর্স নিতে চান, সেগুলো ও সম্ভাব্য গ্রেড দিয়ে যোগ করুন:",
    addToList = "তালিকায় যোগ করুন",
    possibleCourses = "পরিকল্পিত কোর্সসমূহ",
    projectedCgpa = "প্রজেক্টেড CGPA",
    saveAllAsCompleted = "সম্পন্ন কোর্স হিসেবে সংরক্ষণ করুন",

    importCourses = "কোর্স ইমপোর্ট করুন",
    importFromFile = "ইমপোর্ট",
    exportPdf = "PDF হিসেবে Export করুন",
    backupExport = "ব্যাকআপ Export করুন (JSON)",
    backupImport = "ব্যাকআপ Import করুন (JSON)",
    backupExportSuccess = "ব্যাকআপ ফাইল সংরক্ষণ করা হয়েছে",
    backupImportNothingFound = "এই ব্যাকআপ ফাইলে কোনো সঠিক কোর্স পাওয়া যায়নি",
    importFormatHint = "সাপোর্টেড: .csv, .txt, .pdf, অথবা মার্কশিট/transcript-এর ছবি।\n\nসহজ ফরম্যাট: কোর্সের নাম, ক্রেডিট, গ্রেড\nউদাহরণ: Data Structures, 3, A\n\nঅফিসিয়াল transcript (Course Code, Description, Credit, Grade কলাম সহ) সরাসরি সাপোর্ট করে -- আলাদাভাবে ফরম্যাট করার দরকার নেই। OCR সবসময় ১০০% নিখুঁত হয় না -- যোগ করার আগে অবশ্যই preview লিস্টটা দেখে নিশ্চিত হবে, আর ভালো আলোয় তোলা পরিষ্কার ছবি ব্যবহার করবে।",
    importSuccess = "টি কোর্স ইমপোর্ট হয়েছে",
    importNothingFound = "এই ফাইলে কোনো সঠিক কোর্স পাওয়া যায়নি",
    importReviewTitle = "প্রাপ্ত কোর্সসমূহ",
    importAddAll = "সব যোগ করুন",
    importProcessing = "ফাইল পড়া হচ্ছে...",

    menuHome = "হোম",
    menuSettings = "সেটিংস",
    menuAbout = "অ্যাপ সম্পর্কে",
    logout = "লগআউট",
    logoutConfirmTitle = "লগআউট",
    logoutConfirmMessage = "আপনি কি লগআউট করতে চান?",
    yes = "হ্যাঁ",
    no = "না",

    settingsTitle = "সেটিংস",
    departmentSetting = "ডিপার্টমেন্ট",
    universitySetting = "বিশ্ববিদ্যালয়",
    universityHint = "যেমন ADUST",
    semestersSetting = "সেমিস্টার",
    addSemesterHint = "যেমন Spring 2026",
    add = "যোগ করুন",
    noSemesterGroup = "অনির্ধারিত",
    semesterLabel = "সেমিস্টার",
    languageSetting = "অ্যাপ ভাষা",
    darkModeSetting = "ডার্ক মোড",
    themeModeSetting = "থিম",
    themeModeSystem = "সিস্টেম ডিফল্ট",
    themeModeLight = "লাইট",
    themeModeDark = "ডার্ক",
    rateUsTitle = "CGPA ক্যালকুলেটর ভালো লাগছে?",
    rateUsMessage = "Play Store-এ একটা ছোট rating দিলে অনেক সাহায্য হয়, মাত্র কয়েক সেকেন্ডের ব্যাপার।",
    rateUsNow = "এখনই Rate করুন",
    rateUsLater = "পরে",
    rateUsNever = "না, থাক",
    biometricLockSetting = "বায়োমেট্রিক লক",
    biometricLockLabel = "অ্যাপ খুলতে ফিঙ্গারপ্রিন্ট/ফেস প্রয়োজন হবে",
    lockScreenTitle = "অ্যাপ লক করা আছে",
    lockScreenSubtitle = "ফিঙ্গারপ্রিন্ট, ফেস অথবা ডিভাইস PIN দিয়ে আনলক করো",
    lockScreenRetryButton = "আবার চেষ্টা করুন",
    emailVerificationSetting = "ইমেইল ভেরিফিকেশন",
    emailNotVerifiedMessage = "তোমার ইমেইল এখনো ভেরিফাই করা হয়নি।",
    resendVerificationButton = "ভেরিফিকেশন ইমেইল আবার পাঠান",
    verificationEmailSentMessage = "ভেরিফিকেশন ইমেইল পাঠানো হয়েছে -- ইনবক্স চেক করো",
    deleteAccountSetting = "অ্যাকাউন্ট মুছুন",
    deleteAccountButton = "আমার অ্যাকাউন্ট মুছুন",
    deleteAccountConfirmMessage = "এটি তোমার অ্যাকাউন্ট আর সব সংরক্ষিত কোর্স স্থায়ীভাবে মুছে ফেলবে। এটা আর ফিরিয়ে আনা যাবে না। যদি এটা fail করে, তাহলে লগআউট করে আবার লগইন করে চেষ্টা করো।",
    deleteAccountFailedMessage = "অ্যাকাউন্ট মুছতে পারিনি। লগআউট করে আবার লগইন করে চেষ্টা করো।",
    courseNotesHint = "নোট (ঐচ্ছিক) -- সিলেবাস, chapter list ইত্যাদি",
    courseNotesLabel = "নোট",
    viewNotesTitle = "কোর্স নোট",
    gradingScaleSetting = "গ্রেডিং স্কেল",
    gradingScale4 = "4.00 স্কেল",
    gradingScale5 = "5.00 স্কেল",
    gradingScaleNote = "নতুন কোর্স যোগ করার সময় দেখানো গ্রেড অপশন বদলে যাবে। আগে যোগ করা কোর্সগুলোর গ্রেড পয়েন্ট আগের মতোই থাকবে।",
    saveScenarioButton = "Scenario হিসেবে সংরক্ষণ করুন",
    scenarioNameHint = "Scenario-র নাম, যেমন Best Case",
    savedScenariosLabel = "সংরক্ষিত Scenario",
    loadScenarioButton = "লোড করুন",
    scenarioSavedMessage = "Scenario সংরক্ষণ করা হয়েছে",
    scenarioDeletedMessage = "Scenario মুছে ফেলা হয়েছে",
    scenarioLoadedMessage = "Scenario লোড করা হয়েছে",
    changePassword = "পাসওয়ার্ড পরিবর্তন",
    changePasswordSent = "আপনার ইমেইলে পাসওয়ার্ড রিসেট লিংক পাঠানো হয়েছে",
    clearData = "সব কোর্স ডেটা মুছুন",
    clearDataConfirm = "এটি আপনার সব সংরক্ষিত কোর্স স্থায়ীভাবে মুছে ফেলবে। চালিয়ে যাবেন?",
    dataClearedMessage = "সব কোর্স ডেটা মুছে ফেলা হয়েছে",
    appVersion = "অ্যাপ ভার্সন",

    aboutTitle = "অ্যাপ সম্পর্কে",
    aboutDescription = "CGPA ক্যালকুলেটর বিশ্ববিদ্যালয়ের শিক্ষার্থীদের CGPA ট্র্যাক করতে, রিটেক পরিকল্পনা করতে এবং ভবিষ্যৎ ফলাফল প্রজেক্ট করতে সাহায্য করে -- একদম সহজ একটি অ্যাপে।",
    featuresTitle = "ফিচারসমূহ",
    feature1 = "সম্পন্ন কোর্স ও বর্তমান CGPA ট্র্যাক করুন",
    feature2 = "সংরক্ষণ করার আগে রিটেক ফলাফল সিমুলেট করুন",
    feature3 = "প্রজেক্টেড CGPA দিয়ে ভবিষ্যৎ সেমিস্টার পরিকল্পনা করুন",
    feature4 = "CSV বা TXT ফাইল থেকে একসাথে অনেক কোর্স ইমপোর্ট করুন",
    developedBy = "তৈরি করেছেন",
    university = "বিশ্ববিদ্যালয়",
    contact = "যোগাযোগ"
)

val LocalAppStrings = compositionLocalOf { EnglishStrings }

fun stringsFor(lang: AppLanguage): AppStrings = if (lang == AppLanguage.BANGLA) BanglaStrings else EnglishStrings
